### ISSUE TITLE
"Could Not Find Zip Member" Error

### ISSUE THREAD

**Issue by rlockett1121** [konnco/filament-import#122]
Whenever I attempt to import a spreadsheet I get the following error message:
Could not find zip member zip:///srv/app/storage/framework/cache/laravel-excel/{filename}.xlsx#_rels\.rels

Example:
Could not find zip member zip:///srv/app/storage/framework/cache/laravel-excel/laravel-excel-mWjJtWdvcNkTQpfOJwJyuOkIYUAJNRT7.xlsx#_rels\.rels

This issue only came about after I upgraded the project I'm working on to Filament V3 (and subsequently your package to v1.6.1). Changing the file permissions produces no result, and the files that are being looked for (though when I looked at them it looks like they're being created as empty)

Here is a minimal example of a spreadsheet which produced this error when I tried to import it

![image](https://github.com/konnco/filament-import/assets/120379092/72656f94-9a64-43a5-a92f-997aa7f08dfe)

Do you have any idea what's causing this?

Thanks

**Comment by talaridisTh** [comment]
I have the same problem

**Comment by rguttersohn** [comment]
> Make sure your disk is set correctly in filament-import.php config, I had this error and it was related to that. Publish it if you haven't. When the file is created empty it's because it can't get it from the original disk.
> 
> Also make sure you have upgraded this package to the beta release

What did you change the disk to in the config file?

**Comment by gabrieljaime** [comment]
I have the same problem! :(

**Comment by rguttersohn** [comment]
I am also having an issue with getting CSV files to populate the match fields. See here #124 . Anyone else having an issue with using filament v3 and filament-import 2.0.1-beta?

**Comment by adriaardila** [comment]
> > Make sure your disk is set correctly in filament-import.php config, I had this error and it was related to that. Publish it if you haven't. When the file is created empty it's because it can't get it from the original disk.
> > 
> > Also make sure you have upgraded this package to the beta release
> 
> What did you change the disk to in the config file?

I personally use s3, so I set my disk to s3, but I tested it with local and it worked for me too

**Comment by rlockett1121** [comment]
Updating this package to v2.0.0-beta fixed it for me

**Comment by adriaardila** [comment]
> Updating this package to v2.0.0-beta fixed it for me

Ok, then maybe it has to do with the changes I did in the last PR, just to make sure, you are using the local disk right? I will check it later and do a PR fixing it

**Comment by Ryuk88** [comment]
i have the same problem, both with csv files and xlsx files.
Up to version 1.6 with filament 2 everything worked fine. I just upgraded to filament version 3 and filament-import version 2.0.1 beta and as soon as I upload the xls file I have the same error as in the screen.
If instead I load a csv file I get the first screen error.
I tried with single line file as well, but got the same error.

I tried with a clean install of laravel with filament 3 (so without upgrading from version 2 to version 3), installed filament-import but I always have this problem.

Currently everything is local on a mac with m1.
I have the default config for filmanet-import.php

`return [
    'accepted_mimes' => [
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'text/csv',
        'text/plain',
        'csv',
        'txt',
    ],
    'temporary_files' => [
        'disk' => 'local',
        'directory' => 'filament-import',
    ],`

Error with csv file:
<img width="1334" alt="image" src="https://github.com/konnco/filament-import/assets/22523926/0c22bf93-0661-4bd1-a566-7e77408ce471">

Error with XLSX file
<img width="1357" alt="image" src="https://github.com/konnco/filament-import/assets/22523926/4db11f6b-0f85-4ae2-8eaa-9fd0515b648b">

**Comment by gabrieljaime** [comment]
> > Updating this package to v2.0.0-beta fixed it for me
> 
> Ok, then maybe it has to do with the changes I did in the last PR, just to make sure, you are using the local disk right? I will check it later and do a PR fixing it

Yes, im using disk

**Comment by rguttersohn** [comment]
> > > Make sure your disk is set correctly in filament-import.php config, I had this error and it was related to that. Publish it if you haven't. When the file is created empty it's because it can't get it from the original disk.
> > > Also make sure you have upgraded this package to the beta release
> > 
> > 
> > What did you change the disk to in the config file?
> 
> I personally use s3, so I set my disk to s3, but I tested it with local and it worked for me too
> 
> Do you have your livewire tmp storage correctly setup? Might have something to do with that too.

That could be it. I’ll do some more investigating tonight. I have zero LiveWire experience. So it could be that.

**Comment by adriaardila** [comment]
This PR should solve this

https://github.com/konnco/filament-import/pull/125

**Comment by oliwerhelsen** [comment]
Any progress on merging the PR? 🙈

**Comment by rguttersohn** [comment]
> Any progress on merging the PR? 🙈

If you are starting a project, you can point to @adriaardila PR in your composer.json file while we await the merge.

**Comment by helderlj** [comment]
> > Any progress on merging the PR? 🙈
> 
> If you are starting a project, you can point to @adriaardila PR in your composer.json file while we await the merge.

Also waiting on that merge... =/

It did worked with @adriaardila PR. This is how my composer.json looks like:
        "konnco/filament-import": "dev-filament3#5f5019f128f497a6ea6464f94784c63fe0374a29",

**Comment by oliwerhelsen** [comment]
Thanks @helderlj! Worked!

**Comment by albertobenavides** [comment]
Is the merge comming soon? :)

**Comment by aeq-dev** [comment]
Any update here ?

**Comment by nicholaschun** [comment]
upgrading to v2.0.0-beta fixed it for me

**Comment by elmudometal** [comment]
this #125  improvement was not incorporated for the supported v1.6
