### ISSUE TITLE
Import only read one row

### ISSUE THREAD

**Issue by tryoasnafi** [konnco/filament-import#16]
#### Issue description

After updating to 1.0.2, I try to test the import feature and found only one row was inserted in the database.

#### Steps to reproduce the issue

The issue in the file `src/Import.php` at `execute()` function.

```php
DB::transaction(function () {
    foreach ($this->getSpreadsheetData() as $row) {
        $prepareInsert = [];

        foreach ($this->fields as $key => $value) {
            $prepareInsert[$key] = $this->formSchemas[$key]?->doMutateBeforeCreate($row[$value]) ?? $row[$value];
        }

        if ($this->massCreate) {
            $this->model::create($prepareInsert);

            return;
        }

        $model = new $this->model;
        $model->fill($prepareInsert);
        $model->save();
    }
});
```

I figure out the issue in this section
```php
if ($this->massCreate) {
    $this->model::create($prepareInsert);

    return;
}
```
If the `massCreate` is equal to `true` it will run code inside the block, and the problem is you `return;` the function, which makes the loop break and not continues to the next row in the file.

#### What's the expected result?

I expect to import all rows in excel or csv.

#### What's the actual result?

The package just imports only one row from file excel or csv.

#### Additional details / screenshot
**importfile.csv**
![image](https://user-images.githubusercontent.com/61939827/190509959-23d4cf39-5aa0-4b7f-a45e-f56f03df5993.png)

**match data to column**
![image](https://user-images.githubusercontent.com/61939827/190510817-dfeecb18-8eab-4e64-90b3-72abb5088819.png)

**the result**
![image](https://user-images.githubusercontent.com/61939827/190510955-fe596d8c-a02b-4e9d-be9e-639e2c319021.png)

**Comment by tryoasnafi** [comment]
#### My Suggestion to Solve This Problem

I do not fully understand what is `massCreate` function actually does, but this is my approach:

1. You can change return to `continue`, so it will jump to the next iteration and skip the rest of the current iteration.
```php
if ($this->massCreate) {
    $this->model::create($prepareInsert);

    continue;
}
```
2.  You can flip `massCreate` condition
```php
DB::transaction(function () {
    foreach ($this->getSpreadsheetData() as $row) {
        ...

        if (!$this->massCreate) {
            $this->model::fill($prepareInsert)->save();

            return;
        }

        $this->model::create($prepareInsert);
    }
});
```

These two approach works perfectly in my machine, give it a try.

**Comment by frankyso** [comment]
Thanks dude! you're Rock!
