### ISSUE TITLE
'Konnco\FilamentImport\ImportField' is depreciated 

### ISSUE THREAD

**Issue by andrewdwallo** [konnco/filament-import#27]
Intelephense is saying that the ImportField is depreciated. It is still working but it is kind of annoying to have a line crossing through the word because I can't even see the word. Is it a bug? Or is Intelephense just not recognizing it? because it wasn't showing it was depreciated earlier today.. If nothing is depreciated, how do you suggest I remove the line? Thanks!

**Comment by frankyso** [comment]
@andrewdwallo it's still working, we decided to move the files into `Konnco\FilamentImport\Actions\ImportField;` to remove the line just replace `Konnco\FilamentImport\ImportField;` into `Konnco\FilamentImport\Actions\ImportField;`
will update the readme later.

**Comment by andrewdwallo** [comment]
Okay Thank you!
