### ISSUE TITLE
Auto match columns

### ISSUE THREAD

**Issue by Frameck** [konnco/filament-import#37]
### Discussed in https://github.com/konnco/filament-import/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **Frameck** October  5, 2022</sup>
It would be nice to add the ability to choose whether the import should automatically match the columns to the values, because if you have a lot of columns it takes a long time to manually associate them each time.
So if `Auto match columns` is `true` the form with selects doesn't appear and it matches automatically based on the name of the columns.

Something like this:

![Schermata 2022-10-05 alle 12 39 10](https://user-images.githubusercontent.com/77396783/194042061-26ecb653-7295-4eda-a0bc-f68201bc6c52.png)</div>

**Comment by tonypartridge** [comment]
That would be ideal

**Comment by frankyso** [comment]
Hi @Frameck @tonypartridge, the feature has been added on 1.2.6. thanks for your feedback guys :)

**Comment by tonypartridge** [comment]
Amazing!

**Comment by Frameck** [comment]
Hi @frankyso, first of all thank you for this feature, much appreciated.
I've tried the import on the users table with the file below but it doesn't prepopulate the name column

[Test import.xlsx](https://github.com/konnco/filament-import/files/9786525/Test.import.xlsx)
![Screenshot](https://user-images.githubusercontent.com/77396783/195854785-700e1556-a4a0-4cb2-8a67-1759167aad86.png)

**Comment by frankyso** [comment]
Have you update the package?

**Comment by Frameck** [comment]
yes i ran composer update `Upgrading konnco/filament-import (1.2.4 => 1.2.6)`

**Comment by frankyso** [comment]
for the header name, the column must match the intended database field.

Or please share the ListPage code let me check the package again

**Comment by Frameck** [comment]
this is the code i have on the ListPage
```
ImportAction::make()
    ->fields([
        ImportField::make('name'),
        ImportField::make('email'),
        ImportField::make('password'),
    ])
    ->mutateBeforeCreate(function ($row) {
        $row['password'] = Hash::make($row['password']);

        return $row;
    }),
```

**Comment by sprklinginfo** [comment]
is this 'auto match' feature already completed? using version v1.6.0 now and I don't see the option to select 'auto match' in the matching screen.

**Comment by ckeeney** [comment]
It would be nice if this feature was a method that was supposed to return the map of columns so you could configure it.
