### ISSUE TITLE
Upload saves the values as array keys

### ISSUE THREAD

**Issue by ettiennelouw** [konnco/filament-import#4]
Installed the packages and works great just cannot get the uploaded item to save the values, seems like it saves the array keys to the database. not sure if Im doing something wrong.

```
ImportAction::make()
    ->fields([
        ImportField::make('title')
            ->label('Title')
            ->mutateBeforeCreate(fn($string) => Str::lower($string)),
        ImportField::make('slug')
            ->label('Slug')
            ->mutateBeforeCreate(fn($string) => Str::upper($string)),
        ImportField::make('body')
            ->label('Body')
            ->mutateBeforeCreate(fn($string) => Str::upper($string)),
    ], columns:2)
```
![Screenshot 2022-09-12 at 10 01 04](https://user-images.githubusercontent.com/1754421/189602664-f88e5d95-9c2c-4251-8f41-ef6d38d88ed9.png)

Uploaded csv

![Screenshot 2022-09-12 at 10 02 08](https://user-images.githubusercontent.com/1754421/189603058-6e0a9d3d-d052-4c30-a89e-8068044ff116.png)

**Comment by frankyso** [comment]
Fixed, Thanks for noticing,
