### ISSUE TITLE
Save a field from another value field without mapping data

### ISSUE THREAD

**Issue by rizkyanfasafm** [konnco/filament-import#5]
I have password field, and i want to auto assign dependent from birth_date field without using mapping data

![image](https://user-images.githubusercontent.com/24226461/189625172-7018cd78-fb8b-4a0b-bfaa-efa9bd5e9a7b.png)

**Comment by abduromanov** [comment]
Maybe you can check #18 for this enhancement. Thanks

**Comment by frankyso** [comment]
@rizkyanfasafm please install the version #29
