### ISSUE TITLE
It tries to import empty rows

### ISSUE THREAD

**Issue by elfeffe** [konnco/filament-import#50]
We need to check if the row is empty

**Comment by frankyso** [comment]
I have solved the issue on release 1.4.1

**Comment by elfeffe** [comment]
It's still happening.
If I download an Excel file from Google Spreadsheets, it has an error saying $model doesn't exist, because the file is empty.
I had to add

 if($model)
                {
                    $this->doMutateAfterCreate($model, $prepareInsert);
                }

to execute() function
